export const eodiroConsts = {
  OVERLAY_SENTINEL_SPOT: 'overlay-sentinel-spot',
  TITLE_SENTINEL_SPOT: 'title-sentinel-spot',
  MIN_NICKNAME_LENGTH: 2,
  MAX_NICKNAME_LENGTH: 20,
  MIN_PASSWORD_LENGTH: 8,
  EDR_ACCESS_TOKEN_NAME: 'EDR_ACC',
  EDR_REFRESH_TOKEN_NAME: 'EDR_REF',
  LAST_PATH: 'LAST_PATH',
  MIN_POST_TITLE_LENGTH: 1,
  MAX_POST_TITLE_LENGTH: 100,
  MIN_POST_BODY_LENGTH: 1,
  POST_LIST_SLICE_LENGTH: 30,
}
